<a href="https://colab.research.google.com/github/AkshayKulkarni1904/Python/blob/main/Python_Day_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#*Function with Arguments*

**Types of arguments**
- Positional arguments : These are args in which sequence order matters
- Keyword arguments
- Default arguments
- Variable-length arguments

(To solve the above problem, we have keyword args:
- which don't require following order because they directly refer to key-value format
- We must supply 3 values to 3 args
in keywords also we need to provide values equal to number of args
- To solve this we have default arguments
using default args we set static values in declaration
- so when user is not supplying the values, the calling system will take default values
when user is sending values those will be taken otherwise default values will be used
- Rule - we can use positional and keyword args but we should mention positional first and then go with keyword)

### Understanding Function Arguments in Python

Functions in Python allow you to encapsulate reusable blocks of code. Arguments are values that you pass into a function when you call it, allowing the function to perform actions based on those specific inputs. Python supports several types of arguments, each offering different ways to pass and handle data within your functions.

In [1]:
def addition(x,y):
  print('Addition:',x+y)
  print('Multiplication:',x*y)
  print('Subtraction:',x-y)
  print('Division:',x/y)
addition(12,20)

Addition: 32
Multiplication: 240
Subtraction: -8
Division: 0.6


### Positional Arguments

Positional arguments are the most straightforward type of argument. When you call a function, the values you pass are matched to the parameters in the function definition based on their position or order. This means the first value you pass goes to the first parameter, the second value to the second parameter, and so on.

**Example from your code:**

In `def test(x, y, z):`, when you call `test(100, 200, 300)`, `x` becomes `100`, `y` becomes `200`, and `z` becomes `300` because of their order.

In [2]:
#Potional argument
def test(x,y,z):
  print(x,y,z)

test(100,200,300)
test(25,15,67)

100 200 300
25 15 67


In [5]:
def test(x,y,z):
  print('Addition:',x+y+z)
  print('Multiplication:',x*y*z)
  print('Subtraction:',x-y-z)
  print('Division:',x/y/z)
test(12,20,45)
print('\n')
test(5,25,67)

Addition: 77
Multiplication: 10800
Subtraction: -53
Division: 0.013333333333333332


Addition: 97
Multiplication: 8375
Subtraction: -87
Division: 0.0029850746268656717


In [9]:
def info(name,age,sal):
  print("Your name is:",name,"Your age is:",age,'&your salary is:',sal)
info('akshay',23,60000)

Your name is: akshay Your age is: 23 &your salary is: 60000


In [10]:
info(60000,'Ak',23) #when user dosent follow order then output is not as per expection

Your name is: 60000 Your age is: Ak &your salary is: 23


In [11]:
#To solve above problem we have keyword args:
#which doesnt require to follow order because it directly reffers to key-value format
#We must supply 3 values to 3 args
#in keywords also we need to provide values = to number of args
def info(name,age,sal):
  print("Your name is:",name,"Your age is:",age,'&your salary is:',sal)
info(age=23,name='akshay',sal=60000)

Your name is: akshay Your age is: 23 &your salary is: 60000


### Keyword Arguments

Keyword arguments allow you to pass values to function parameters by explicitly naming them. This removes the dependency on the order of arguments. You can pass arguments in any order as long as you specify the parameter name for each value.

**Why use them?**
- **Readability:** Makes code clearer by indicating the purpose of each argument.
- **Flexibility:** Allows you to skip or reorder arguments when their names are known.
- **Avoiding errors:** Prevents issues that arise from incorrect positional ordering, as seen when `info(60000, 'Ak', 23)` resulted in incorrect assignment in your example.

**Example from  code:**

`info(age=23, name='akshay', sal=60000)` explicitly assigns values to `age`, `name`, and `sal` regardless of their position in the call.

In [12]:
#in keywords also we need to provide values = to number of args
#To solve this we have default arguments
#using default args we set static values in decleration
#so when user is not supplying the values from calling system will take default values
#when user is sending values those will be take otherwise default values will be used
def info(name='Guest',age='24',sal=40000):
  print("Your name is:",name,"Your age is:",age,'&your salary is:',sal)
info('akshay',23)

Your name is: akshay Your age is: 23 &your salary is: 40000


In [13]:
#Rule - we can use potional and keywords args but we should mention positional 1st and then go with keyword
info('Akshay',sal=75000,age=22)

Your name is: Akshay Your age is: 22 &your salary is: 75000


### Default Arguments

Default arguments allow you to provide a default value for a parameter in the function definition. If the caller does not provide a value for that parameter, the default value is used. If a value is provided, it overrides the default.

**Benefits:**
- **Optional parameters:** Makes some function parameters optional, reducing the need for multiple functions with similar functionality.
- **Backward compatibility:** Allows adding new parameters to existing functions without breaking old code that doesn't provide values for the new parameters.

**Example from  code:**

In `def info(name='Guest', age='24', sal=40000):`, `name`, `age`, and `sal` all have default values. When `info('akshay', 23)` is called, `name` and `age` are overridden, but `sal` uses its default value of `40000` because it wasn't provided.

#Variable length types
- 1.Variable length position args
- 2.Variable length keyword args

In [17]:
#Variable length args ---> *args (to pack multiple values)
#when user doesnot have a strict requirnment of sending the values to the arguments and values from one caling to another
def test(*n):
  print(n)
test(10,20,30)

(10, 20, 30)


### Variable-Length Positional Arguments (`*args`)

Sometimes you might not know in advance how many positional arguments a function will receive. Python's `*args` allows a function to accept an arbitrary number of positional arguments. These arguments are then gathered into a tuple within the function.

The asterisk (`*`) before the parameter name (e.g., `*n`) indicates that any additional positional arguments passed to the function should be collected into a tuple named `n`.

**Example from  code:**

In `def test(*n):`, the function can accept any number of positional arguments, such as `test(10, 20, 30)`, which are then accessed as a tuple `(10, 20, 30)` inside the function.

In [19]:
#2.Variable length keyword args ---> **kwargs
def test(**x):
 print(x)

test(num1=10,num2=20,num3=30)

{'num1': 10, 'num2': 20, 'num3': 30}


In [20]:
test(name='Ak',age=34,sal=45000)

{'name': 'Ak', 'age': 34, 'sal': 45000}


### Variable-Length Keyword Arguments (`**kwargs`)

Similar to `*args`, `**kwargs` (keyword arguments) allows a function to accept an arbitrary number of keyword arguments. These arguments are then gathered into a dictionary within the function, where keys are the argument names and values are their corresponding values.

The double asterisk (`**`) before the parameter name (e.g., `**x`) indicates that any additional keyword arguments passed to the function should be collected into a dictionary named `x`.

**Example from  code:**

`test(num1=10, num2=20, num3=30)` collects these into a dictionary `{'num1': 10, 'num2': 20, 'num3': 30}` within the `test` function.

In [25]:
#when compbining both it is possible but follow rule
#first we need positional n then keyword

def sample(*args,**kwrgs):
  print(args,kwrgs)

sample(10,20,30,num1=350,num2=420)

(10, 20, 30) {'num1': 350, 'num2': 420}


### Combining `*args` and `**kwargs`

You can use both `*args` and `**kwargs` in the same function definition. When doing so, there's a strict order that must be followed:

1.  **Normal positional arguments**
2.  **Default arguments**
3.  `*args` (variable-length positional arguments)
4.  `**kwargs` (variable-length keyword arguments)

**Example from code:**

`def sample(*args, **kwrgs):` correctly defines a function that can accept any number of positional arguments (collected in `args`) and any number of keyword arguments (collected in `kwrgs`). When `sample(10, 20, 30, num1=350, num2=420)` is called, `args` becomes `(10, 20, 30)` and `kwrgs` becomes `{'num1': 350, 'num2': 420}`.

## Practice Questions

1.  **Positional vs. Keyword Arguments:**
    Given the function `def greet(name, message): print(f'{name}, {message}')`
    a. How would you call `greet` using only positional arguments to print "Alice, Hello!"?
    b. How would you call `greet` using only keyword arguments to print "Bob, Goodbye!"?
    c. What happens if you call `greet(message='Hi', 'Charlie')`? Explain why.

2.  **Default Arguments:**
    Modify the following function `def calculate_area(length, width): return length * width` so that `width` has a default value of `10`.
    a. How would you call the modified function to calculate the area of a rectangle with length `5` and width `20`?
    b. How would you call it to calculate the area of a rectangle with length `7` using the default width?

3.  **Variable-Length Positional Arguments (`*args`):**
    Write a function `sum_all(*numbers)` that takes any number of numerical arguments and returns their sum.
    a. Call this function with `sum_all(1, 2, 3)`.
    b. Call this function with `sum_all(10, 20, 30, 40, 50)`.

4.  **Variable-Length Keyword Arguments (`**kwargs`):**
    Write a function `print_user_details(**details)` that takes an arbitrary number of keyword arguments (like `name='Alice'`, `age=30`, `city='New York'`) and prints each key-value pair.
    a. Call this function with `print_user_details(name='Eve', occupation='Engineer')`.
    b. Call this function with `print_user_details(item='Book', price=25.99, quantity=2)`.

5.  **Combining `*args` and `**kwargs`:**
    Write a function `process_order(order_id, *items, **details)` that takes an `order_id` (positional), any number of `items` (positional arguments collected in `*items`), and any additional `details` (keyword arguments collected in `**details`). The function should print the `order_id`, the list of `items`, and the `details` dictionary.
    a. Call this function with `process_order(101, 'apple', 'banana', 'orange', customer='John', total=15.50)`.

## Solutions to Practice Questions

### 1. Positional vs. Keyword Arguments

In [40]:
def greet(name, message):
  print(name,message)

#Positional arguments
greet('Raj', 'Hello!')

#Keyword arguments
greet(message='Goodbye!', name='RAj')

# What happens if you call greet(message='Hi', 'name')? Explain why.
# This will raise a SyntaxError because positional arguments cannot follow keyword arguments.
# Python requires that all positional arguments come before any keyword arguments in a function call.
# try:
#     greet(message='Hi', 'user')
# except SyntaxError as e:
#     print(f"Error: {e}. Positional argument follows keyword argument.")

Raj Hello!
RAj Goodbye!


### 2. Default Arguments

In [45]:
def calculate_area(length, width=10):
  return length * width

area1 = calculate_area(5, 20)
print("Area with length 5 and width 20: {area1}")

area2 = calculate_area(7)
print("Area with length 7 (default width 10): {area2}")

Area with length 5 and width 20: {area1}
Area with length 7 (default width 10): {area2}


### 3. Variable-Length Positional Arguments (`*args`)

In [44]:
def sum_all(*numbers):
  return sum(numbers)

result1 = sum_all(1, 2, 3)
print("Sum of (1, 2, 3): {result1}")

result2 = sum_all(10, 20, 30, 40, 50)
print("Sum of (10, 20, 30, 40, 50): {result2}")

Sum of (1, 2, 3): {result1}
Sum of (10, 20, 30, 40, 50): {result2}


### 4. Variable-Length Keyword Arguments (`**kwargs`)

In [42]:
def print_user_details(**details):
  for key, value in details.items():
    print(f"{key.replace('_', ' ').title()}: {value}")

print("User Details 1:")
print_user_details(name='Harsh', occupation='Engineer')
print("\n")

print("User Details 2:")
print_user_details(item='Book', price=25.99, quantity=2)

User Details 1:
Name: Harsh
Occupation: Engineer


User Details 2:
Item: Book
Price: 25.99
Quantity: 2


### 5. Combining `*args` and `**kwargs`

In [41]:
def process_order(order_id, *items, **details):
  print(f"Order ID: {order_id}")
  print(f"Items: {items}")
  print(f"Details: {details}")

process_order(101, 'apple', 'banana', 'orange', customer='Harsh', total=15.50)

Order ID: 101
Items: ('apple', 'banana', 'orange')
Details: {'customer': 'Harsh', 'total': 15.5}
